import torch


class UniformParameterSpace:
    """
    Uniform sampler for a rectangular parameter domain.

    Each scalar parameter is sampled independently from the half-open interval
    [low, high). The returned tensor has the requested shape and data type.

    This sampler is suitable for global effective-dimension estimation when
    the parameter measure is uniform over a hyper-rectangular domain.

    Args:
        low:
            Inclusive lower bound of the uniform distribution.

        high:
            Exclusive upper bound of the uniform distribution.

        shape:
            Shape of one parameter sample. This should normally equal
            `net.qlayers.weights.shape`.

        dtype:
            Data type of generated samples. Default: torch.float64.
    """

    def __init__(self, low, high, shape, dtype=torch.float64):
        """
        Initialize a uniform parameter-space sampler.

        Args:
            low:
                Inclusive lower sampling bound.

            high:
                Exclusive upper sampling bound.

            shape:
                Tensor shape for each sampled parameter vector.

            dtype:
                Torch data type of generated samples.
        """
        self.low = low
        self.high = high
        self.shape = shape
        self.dtype = dtype

    def sample(self):
        """
        Draw one parameter tensor from the uniform parameter space.

        Every tensor entry is independently sampled from [low, high).

        Returns:
            torch.Tensor:
                A tensor with shape `self.shape`, dtype `self.dtype`, and
                independently uniform entries.
        """
        return torch.empty(self.shape, dtype=self.dtype).uniform_(
            self.low,
            self.high,
        )


class EpsilonBallParameterSpace:
    """
    Uniform sampler over the volume of an epsilon-ball around a centre tensor.

    The parameter tensor is flattened into a vector of dimension d. A sample is
    generated by choosing a uniformly distributed direction on the unit sphere
    and a radius with distribution:

        r = epsilon * u^(1 / d),  where u ~ Uniform(0, 1).

    The exponent 1/d is necessary for samples to be uniform over the ball
    volume. Sampling the radius directly as epsilon * u would over-sample
    points near the centre.

    Args:
        center:
            Tensor defining the centre of the epsilon-ball. A detached copy is
            stored, so later external changes to this tensor do not affect the
            sampler.

        epsilon:
            Positive radius of the ball, measured using the Euclidean norm of
            the flattened parameter tensor.

        generator:
            Optional PyTorch random-number generator. Pass a seeded generator
            to obtain reproducible samples.
    """

    def __init__(self, center, epsilon, generator=None):
        """
        Initialize an epsilon-ball parameter-space sampler.

        Args:
            center:
                Centre of the local parameter region.

            epsilon:
                Positive Euclidean radius of the local parameter region.

            generator:
                Optional random-number generator.

        Raises:
            ValueError:
                If epsilon is zero or negative.
        """
        if epsilon <= 0:
            raise ValueError("epsilon must be positive")

        self.center = center.detach().clone()
        self.epsilon = epsilon
        self.generator = generator
        self.dimension = self.center.numel()

    def sample(self):
        """
        Draw one parameter tensor uniformly from the epsilon-ball.

        A standard Gaussian vector is normalized to obtain an isotropic random
        direction. The radius is sampled as epsilon * u^(1/d), producing a
        uniform distribution over the d-dimensional ball volume.

        Returns:
            torch.Tensor:
                Tensor with the same shape, dtype, and device as `center`.
                It satisfies:

                    ||sample - center||_2 <= epsilon

                after flattening both tensors.
        """
        direction = torch.randn(
            self.dimension,
            dtype=self.center.dtype,
            device=self.center.device,
            generator=self.generator,
        )

        direction = direction / torch.linalg.vector_norm(direction)

        radius = self.epsilon * torch.rand(
            (),
            dtype=self.center.dtype,
            device=self.center.device,
            generator=self.generator,
        ).pow(1.0 / self.dimension)

        return (self.center.reshape(-1) + radius * direction).reshape_as(self.center)